PCI: endpoint: functions/pci-epf-test: Fix compiler error
Commit 812828eb5072 ("PCI: endpoint: Fix ->set_msix() to take BIR
and offset as arguments") was created before adding deferred
core initialization support in commit 5e50ee27d4a5 ("PCI: pci-epf-test:
Add support to defer core initialization").
However since deferred core initialization was merged before
re-designing MSI-X support, it caused the following compiler error.

drivers/pci/endpoint/functions/pci-epf-test.c:697:12: error: ‘epf_test’ undeclared (first use in this function);

Fix the compilation error here.

Fixes: 812828eb5072 ("PCI: endpoint: Fix ->set_msix() to take BIR and offset as arguments")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Kishon Vijay Abraham I <kishon@ti.com>